In [49]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

In [50]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

In [51]:
print(X_train, y_train)

[[4.6 3.6 1.  0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.3 2.5 5.  1.9]
 [6.4 3.2 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.

In [52]:
X_train = (X_train - X_train.min(axis=0)) / (X_train.max(axis=0) - X_train.min(axis=0))
X_test = (X_test - X_test.min(axis=0)) / (X_test.max(axis=0) - X_test.min(axis=0))

In [53]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder(sparse=False)
y_train = y_train.reshape(len(y_train), 1)
y_train = onehot_encoder.fit_transform(y_train)
print(y_train)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0.

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [54]:
onehot_encoder = OneHotEncoder(sparse=False)
y_test = y_test.reshape(len(y_test), 1)
y_test = onehot_encoder.fit_transform(y_test)
print(y_test)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [55]:
def softmax(x):
  return np.exp(x) / np.sum(np.exp(x))

In [56]:
def loss_function(y_predict, y_label):
  return np.sum(-y_label*np.log(y_predict), axis=0)

In [57]:
def loss_function_derivative(y_predict, y_label, x):
  return np.matmul(x.reshape((len(x), 1)), (y_predict - y_label.reshape((1, len(y_predict)))))

In [58]:
def predict(x, weights):
  return softmax(np.dot(x, weights))

In [59]:
def batch_gradient_descent(X, y, W): # update for each epoch
  error = 0.0
  loss = 0.0
  for x_el, y_el in zip(X, y):
    y_pred = predict(x_el, W)
    error += loss_function(y_pred, y_el)
    loss += loss_function_derivative(y_pred, y_el, x_el)
  W -= alpha / len(X) * loss
  error /= len(y)
  return W, error

In [60]:
def stochastic_gradient_descent(X, y, W): # update for each iteration
  error = 0.0
  for x_el, y_el in zip(X, y):
    y_pred = predict(x_el, W)
    error += loss_function(y_pred, y_el)
    loss = loss_function_derivative(y_pred, y_el, x_el)
    W -= alpha * loss
  error /= len(y)
  return W, error

In [61]:
def mini_batch_gradient_descent(X, y, W, n): # update for n iterations
  error = 0.0
  loss = 0.0
  iter = 0
  for x_el, y_el in zip(X, y):
    iter += 1
    y_pred = predict(x_el, W)
    error += loss_function(y_pred, y_el)
    loss += loss_function_derivative(y_pred, y_el, x_el)
    if iter % n == 0:
      W -= alpha / n * loss
      loss = 0.0
  error /= len(y)
  return W, error

In [62]:
def train(X, y, epochs, alpha, gradient_descent, mini_batch = 10): # gradient_descent (1-batch, 2-stochastic, 3-mini_batch)
  input_size = 4
  output_size = 3
  X = np.insert(X, 0, np.ones(len(X)), axis=1)
  W = np.random.randn(input_size + 1, output_size)
  for i in range(epochs):
    if gradient_descent == 1:
      W, error = batch_gradient_descent(X, y, W)
    elif gradient_descent == 2:
      W, error = stochastic_gradient_descent(X, y, W)
    elif gradient_descent == 3:
      W, error = mini_batch_gradient_descent(X, y, W, mini_batch)
    print('Epoch ' + str(i + 1) + ' Error: ' + str(error))
  return W

In [63]:
epochs = 2000
alpha = 0.5
W = train(np.array(X_train), np.array(y_train), epochs, alpha, 1)

error = 0.0
for x_el, y_el in zip(np.insert(np.array(X_test), 0, np.ones(len(np.array(X_test))), axis=1), np.array(y_test)):
  y_pred = predict(x_el, W)
  error += loss_function(y_pred, y_el)
error /= len(np.array(y_test))
print('Error over test set: ' + str(error))

Epoch 1 Error: 1.4229072726543393
Epoch 2 Error: 1.3157928263680696
Epoch 3 Error: 1.249693571610767
Epoch 4 Error: 1.201882657594159
Epoch 5 Error: 1.162875085085242
Epoch 6 Error: 1.1287216021051478
Epoch 7 Error: 1.0976854448704938
Epoch 8 Error: 1.0689459044999101
Epoch 9 Error: 1.0420801606432688
Epoch 10 Error: 1.0168457197036778
Epoch 11 Error: 0.9930847922615944
Epoch 12 Error: 0.9706808014390762
Epoch 13 Error: 0.9495381865540703
Epoch 14 Error: 0.9295729595328263
Epoch 15 Error: 0.9107083212228684
Epoch 16 Error: 0.8928726699861494
Epoch 17 Error: 0.8759987265195169
Epoch 18 Error: 0.8600231592980824
Epoch 19 Error: 0.8448864154092426
Epoch 20 Error: 0.8305326188505191
Epoch 21 Error: 0.81690947570799
Epoch 22 Error: 0.8039681631889625
Epoch 23 Error: 0.7916631971137419
Epoch 24 Error: 0.7799522801535101
Epoch 25 Error: 0.7687961358950225
Epoch 26 Error: 0.7581583342925848
Epoch 27 Error: 0.7480051135365249
Epoch 28 Error: 0.7383052024728263
Epoch 29 Error: 0.7290296467609525

In [64]:
epochs = 2000
alpha = 0.1
W = train(np.array(X_train), np.array(y_train), epochs, alpha, 2)

error = 0.0
for x_el, y_el in zip(np.insert(np.array(X_test), 0, np.ones(len(np.array(X_test))), axis=1), np.array(y_test)):
  y_pred = predict(x_el, W)
  error += loss_function(y_pred, y_el)
error /= len(np.array(y_test))
print('Error over test set: ' + str(error))

Epoch 1 Error: 0.7830467614380768
Epoch 2 Error: 0.5986210008614397
Epoch 3 Error: 0.5213166251136324
Epoch 4 Error: 0.47311812272521375
Epoch 5 Error: 0.4386394525133982
Epoch 6 Error: 0.4120476532373498
Epoch 7 Error: 0.39055619598068453
Epoch 8 Error: 0.3726177703620171
Epoch 9 Error: 0.35728367330598054
Epoch 10 Error: 0.3439312789002657
Epoch 11 Error: 0.3321313853491215
Epoch 12 Error: 0.32157686981514716
Epoch 13 Error: 0.3120413425872313
Epoch 14 Error: 0.3033537859747799
Epoch 15 Error: 0.29538229426771573
Epoch 16 Error: 0.28802327329381694
Epoch 17 Error: 0.2811940550819133
Epoch 18 Error: 0.27482772307847986
Epoch 19 Error: 0.26886940961208566
Epoch 20 Error: 0.26327359792768906
Epoch 21 Error: 0.25800212417125107
Epoch 22 Error: 0.2530226761060843
Epoch 23 Error: 0.24830765013281084
Epoch 24 Error: 0.24383327056857257
Epoch 25 Error: 0.23957890344628877
Epoch 26 Error: 0.23552651634787874
Epoch 27 Error: 0.23166024909845712
Epoch 28 Error: 0.22796606949199807
Epoch 29 Erro

In [65]:
epochs = 2000
alpha = 0.5
W = train(np.array(X_train), np.array(y_train), epochs, alpha, 3, 50)

error = 0.0
for x_el, y_el in zip(np.insert(np.array(X_test), 0, np.ones(len(np.array(X_test))), axis=1), np.array(y_test)):
  y_pred = predict(x_el, W)
  error += loss_function(y_pred, y_el)
error /= len(np.array(y_test))
print('Error over test set: ' + str(error))

Epoch 1 Error: 1.4296132792547918
Epoch 2 Error: 1.270432318375754
Epoch 3 Error: 1.1779739318599156
Epoch 4 Error: 1.113457759726903
Epoch 5 Error: 1.0605765361225836
Epoch 6 Error: 1.0143705772192106
Epoch 7 Error: 0.9732897162420483
Epoch 8 Error: 0.9365880115678517
Epoch 9 Error: 0.9037069410750014
Epoch 10 Error: 0.874159346861521
Epoch 11 Error: 0.8475138458798627
Epoch 12 Error: 0.8233929191122796
Epoch 13 Error: 0.8014699322962214
Epoch 14 Error: 0.781464315650434
Epoch 15 Error: 0.7631359590537463
Epoch 16 Error: 0.7462796278736001
Epoch 17 Error: 0.7307198162324837
Epoch 18 Error: 0.716306201879042
Epoch 19 Error: 0.7029097304763913
Epoch 20 Error: 0.6904192913760233
Epoch 21 Error: 0.6787389199054474
Epoch 22 Error: 0.6677854541921335
Epoch 23 Error: 0.6574865772718109
Epoch 24 Error: 0.6477791821680972
Epoch 25 Error: 0.6386080059154167
Epoch 26 Error: 0.6299244867064026
Epoch 27 Error: 0.6216858058347584
Epoch 28 Error: 0.6138540826404858
Epoch 29 Error: 0.6063956962194474